import "bootstrap/scss/bootstrap.scss";
import './globals.scss'

import type { Metadata } from 'next'
import Script from "next/script";

export const metadata: Metadata = {
  title: 'PUOK',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
      <head>
        <Script
          src="/_next/static/bootstrap.js"
        />
      </head>
      <body>
        {children}
      </body>
    </html>
  )
}